// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes apiKeyAuthContextKey = "ApiKeyAuth.Scopes"
)

// Defines values for ClosedDayStatus.
const (
	ClosedDayStatusClosed ClosedDayStatus = "closed"
)

// Valid indicates whether the value is a known member of the ClosedDayStatus enum.
func (e ClosedDayStatus) Valid() bool {
	switch e {
	case ClosedDayStatusClosed:
		return true
	default:
		return false
	}
}

// Defines values for DayStatus.
const (
	DayStatusClosed         DayStatus = "closed"
	DayStatusNoAvailability DayStatus = "no-availability"
	DayStatusOpen           DayStatus = "open"
)

// Valid indicates whether the value is a known member of the DayStatus enum.
func (e DayStatus) Valid() bool {
	switch e {
	case DayStatusClosed:
		return true
	case DayStatusNoAvailability:
		return true
	case DayStatusOpen:
		return true
	default:
		return false
	}
}

// Defines values for OpenDayStatus.
const (
	Open OpenDayStatus = "open"
)

// Valid indicates whether the value is a known member of the OpenDayStatus enum.
func (e OpenDayStatus) Valid() bool {
	switch e {
	case Open:
		return true
	default:
		return false
	}
}

// Booking A booking record.
type Booking struct {
	// CreatedAt Server-assigned creation timestamp.
	CreatedAt time.Time `json:"createdAt"`

	// DurationMinutesSnapshot Snapshot of the event type's duration at booking time, in minutes.
	DurationMinutesSnapshot DurationMinutes `json:"durationMinutesSnapshot"`

	// EventTypeName Snapshot of the event type's name at booking time.
	EventTypeName string `json:"eventTypeName"`

	// EventTypeSlug Slug of the event type at booking time. May be stale if the slug is later edited.
	EventTypeSlug EventTypeSlug `json:"eventTypeSlug"`

	// GuestEmail RFC 5322 email address.
	GuestEmail EmailAddress `json:"guestEmail"`
	GuestName  string       `json:"guestName"`
	GuestNotes *string      `json:"guestNotes,omitempty"`

	// Id Server-assigned booking identifier (UUID v4).
	Id BookingId `json:"id"`

	// StartTime Booking start time (ISO 8601 with offset).
	StartTime time.Time `json:"startTime"`
}

// BookingCreate Body for creating a new booking under an event type.
type BookingCreate struct {
	// GuestEmail RFC 5322 email address.
	GuestEmail EmailAddress `json:"guestEmail"`
	GuestName  string       `json:"guestName"`
	GuestNotes *string      `json:"guestNotes,omitempty"`

	// StartTime Chosen slot start time. Must exactly match an available slot returned by the slot-picker endpoint.
	StartTime time.Time `json:"startTime"`
}

// BookingId Server-assigned booking identifier (UUID v4).
type BookingId = openapi_types.UUID

// CatalogResponse Response for the public event-type catalog.
type CatalogResponse struct {
	// EventTypes All currently active event types, in display order.
	EventTypes []PublicEventType `json:"eventTypes"`

	// Timezone IANA timezone the times throughout the API are interpreted in.
	Timezone IanaTimezone `json:"timezone"`
}

// ClosedDay A day on which no bookings can occur.
type ClosedDay struct {
	Status ClosedDayStatus `json:"status"`
}

// ClosedDayStatus defines model for ClosedDay.Status.
type ClosedDayStatus string

// DaySlots One day of the slot-picker response.
type DaySlots struct {
	// Date Calendar date in the configured timezone.
	Date IsoDate `json:"date"`

	// Slots Available slot start times for this day (offset reflects the configured timezone). Empty unless `status` = `open`.
	Slots []time.Time `json:"slots"`

	// Status Status of a single day in the slot picker response.
	Status DayStatus `json:"status"`
}

// DayStatus Status of a single day in the slot picker response.
type DayStatus string

// DurationMinutes Positive event duration, in whole minutes.
type DurationMinutes = int32

// EmailAddress RFC 5322 email address.
type EmailAddress = openapi_types.Email

// Error Error envelope returned for any non-2xx response.
type Error struct {
	// Code Stable error code for programmatic handling.
	Code string `json:"code"`

	// Message Human-readable message; safe to display to end users.
	Message string `json:"message"`
}

// EventType An event type as visible to the owner (includes the active flag).
type EventType struct {
	Active      bool   `json:"active"`
	Description string `json:"description"`

	// DurationMinutes Positive event duration, in whole minutes.
	DurationMinutes DurationMinutes `json:"durationMinutes"`
	Name            string          `json:"name"`

	// Slug URL-friendly identifier for an event type. Lowercase, alphanumeric, hyphen-separated.
	Slug EventTypeSlug `json:"slug"`
}

// EventTypeCreate Body for creating a new event type. The `active` flag defaults to true on creation.
type EventTypeCreate struct {
	Description string `json:"description"`

	// DurationMinutes Positive event duration, in whole minutes.
	DurationMinutes DurationMinutes `json:"durationMinutes"`
	Name            string          `json:"name"`

	// Slug URL-friendly identifier for an event type. Lowercase, alphanumeric, hyphen-separated.
	Slug EventTypeSlug `json:"slug"`
}

// EventTypeSlug URL-friendly identifier for an event type. Lowercase, alphanumeric, hyphen-separated.
type EventTypeSlug = string

// EventTypeUpdate Body for partially updating an event type. Any subset of fields may be present;
// omitted fields are unchanged. Editing `durationMinutes` does not affect existing
// bookings (each booking carries its own duration snapshot). Editing `slug` is subject
// to the same format and uniqueness rules as creation.
type EventTypeUpdate struct {
	Active      *bool   `json:"active,omitempty"`
	Description *string `json:"description,omitempty"`

	// DurationMinutes Positive event duration, in whole minutes.
	DurationMinutes *DurationMinutes `json:"durationMinutes,omitempty"`
	Name            *string          `json:"name,omitempty"`

	// Slug URL-friendly identifier for an event type. Lowercase, alphanumeric, hyphen-separated.
	Slug *EventTypeSlug `json:"slug,omitempty"`
}

// HhMm Wall-clock time as HH:MM (24h, no seconds), interpreted in the configured timezone.
type HhMm = string

// IanaTimezone IANA timezone identifier, e.g. "Europe/Moscow".
type IanaTimezone = string

// IsoDate ISO 8601 calendar date in YYYY-MM-DD form, interpreted in the configured timezone.
type IsoDate = openapi_types.Date

// OpenDay A day with an open working window. `end` must be strictly greater than `start`.
type OpenDay struct {
	// End Wall-clock time as HH:MM (24h, no seconds), interpreted in the configured timezone.
	End HhMm `json:"end"`

	// Start Wall-clock time as HH:MM (24h, no seconds), interpreted in the configured timezone.
	Start  HhMm          `json:"start"`
	Status OpenDayStatus `json:"status"`
}

// OpenDayStatus defines model for OpenDay.Status.
type OpenDayStatus string

// OwnerSettings Owner-configurable settings. Singleton resource.
type OwnerSettings struct {
	// Timezone IANA timezone identifier, e.g. "Europe/Moscow".
	Timezone IanaTimezone `json:"timezone"`

	// WorkingHours Weekly working-hours schedule, with one entry per day of the week.
	WorkingHours WorkingHoursByDay `json:"workingHours"`
}

// PublicEventType An event type as visible to guests on the public catalog (always active).
type PublicEventType struct {
	Description string `json:"description"`

	// DurationMinutes Positive event duration, in whole minutes.
	DurationMinutes DurationMinutes `json:"durationMinutes"`
	Name            string          `json:"name"`

	// Slug URL-friendly identifier for an event type. Lowercase, alphanumeric, hyphen-separated.
	Slug EventTypeSlug `json:"slug"`
}

// SlotPickerResponse Response for the slot-picker endpoint. Always covers exactly 14 consecutive days.
type SlotPickerResponse struct {
	// Days 14 day entries from `windowStart` to `windowEnd`, oldest first.
	Days []DaySlots `json:"days"`

	// Timezone IANA timezone the times are interpreted in.
	Timezone IanaTimezone `json:"timezone"`

	// WindowEnd Last date of the booking window (inclusive). Always equals `windowStart` + 13 days.
	WindowEnd IsoDate `json:"windowEnd"`

	// WindowStart First date of the booking window (inclusive), in the configured timezone.
	WindowStart IsoDate `json:"windowStart"`
}

// WorkingDay A single day's schedule: either closed, or an open interval [start, end). Discriminated by `status`.
type WorkingDay struct {
	union json.RawMessage
}

// WorkingHoursByDay Weekly working-hours schedule, with one entry per day of the week.
type WorkingHoursByDay struct {
	// Friday A single day's schedule: either closed, or an open interval [start, end). Discriminated by `status`.
	Friday WorkingDay `json:"friday"`

	// Monday A single day's schedule: either closed, or an open interval [start, end). Discriminated by `status`.
	Monday WorkingDay `json:"monday"`

	// Saturday A single day's schedule: either closed, or an open interval [start, end). Discriminated by `status`.
	Saturday WorkingDay `json:"saturday"`

	// Sunday A single day's schedule: either closed, or an open interval [start, end). Discriminated by `status`.
	Sunday WorkingDay `json:"sunday"`

	// Thursday A single day's schedule: either closed, or an open interval [start, end). Discriminated by `status`.
	Thursday WorkingDay `json:"thursday"`

	// Tuesday A single day's schedule: either closed, or an open interval [start, end). Discriminated by `status`.
	Tuesday WorkingDay `json:"tuesday"`

	// Wednesday A single day's schedule: either closed, or an open interval [start, end). Discriminated by `status`.
	Wednesday WorkingDay `json:"wednesday"`
}

// apiKeyAuthContextKey is the context key for ApiKeyAuth security scheme
type apiKeyAuthContextKey string

// AdminEventTypesCreateJSONRequestBody defines body for AdminEventTypesCreate for application/json ContentType.
type AdminEventTypesCreateJSONRequestBody = EventTypeCreate

// AdminEventTypesUpdateJSONRequestBody defines body for AdminEventTypesUpdate for application/json ContentType.
type AdminEventTypesUpdateJSONRequestBody = EventTypeUpdate

// AdminSettingsUpdateJSONRequestBody defines body for AdminSettingsUpdate for application/json ContentType.
type AdminSettingsUpdateJSONRequestBody = OwnerSettings

// PublicEventTypesBookJSONRequestBody defines body for PublicEventTypesBook for application/json ContentType.
type PublicEventTypesBookJSONRequestBody = BookingCreate

// AsClosedDay returns the union data inside the WorkingDay as a ClosedDay
func (t WorkingDay) AsClosedDay() (ClosedDay, error) {
	var body ClosedDay
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromClosedDay overwrites any union data inside the WorkingDay as the provided ClosedDay
func (t *WorkingDay) FromClosedDay(v ClosedDay) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeClosedDay performs a merge with any union data inside the WorkingDay, using the provided ClosedDay
func (t *WorkingDay) MergeClosedDay(v ClosedDay) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOpenDay returns the union data inside the WorkingDay as a OpenDay
func (t WorkingDay) AsOpenDay() (OpenDay, error) {
	var body OpenDay
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOpenDay overwrites any union data inside the WorkingDay as the provided OpenDay
func (t *WorkingDay) FromOpenDay(v OpenDay) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOpenDay performs a merge with any union data inside the WorkingDay, using the provided OpenDay
func (t *WorkingDay) MergeOpenDay(v OpenDay) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t WorkingDay) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *WorkingDay) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /admin/bookings)
	AdminBookingsList(c *gin.Context)

	// (DELETE /admin/bookings/{id})
	AdminBookingsCancel(c *gin.Context, id BookingId)

	// (GET /admin/event-types)
	AdminEventTypesList(c *gin.Context)

	// (POST /admin/event-types)
	AdminEventTypesCreate(c *gin.Context)

	// (GET /admin/event-types/{slug})
	AdminEventTypesGet(c *gin.Context, slug EventTypeSlug)

	// (PATCH /admin/event-types/{slug})
	AdminEventTypesUpdate(c *gin.Context, slug EventTypeSlug)

	// (GET /admin/settings)
	AdminSettingsGet(c *gin.Context)

	// (PUT /admin/settings)
	AdminSettingsUpdate(c *gin.Context)

	// (GET /event-types)
	PublicEventTypesList(c *gin.Context)

	// (GET /event-types/{slug})
	PublicEventTypesGet(c *gin.Context, slug EventTypeSlug)

	// (POST /event-types/{slug}/bookings)
	PublicEventTypesBook(c *gin.Context, slug EventTypeSlug)

	// (GET /event-types/{slug}/slots)
	PublicEventTypesSlots(c *gin.Context, slug EventTypeSlug)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// AdminBookingsList operation middleware
func (siw *ServerInterfaceWrapper) AdminBookingsList(c *gin.Context) {

	c.Set(string(ApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AdminBookingsList(c)
}

// AdminBookingsCancel operation middleware
func (siw *ServerInterfaceWrapper) AdminBookingsCancel(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id BookingId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(ApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AdminBookingsCancel(c, id)
}

// AdminEventTypesList operation middleware
func (siw *ServerInterfaceWrapper) AdminEventTypesList(c *gin.Context) {

	c.Set(string(ApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AdminEventTypesList(c)
}

// AdminEventTypesCreate operation middleware
func (siw *ServerInterfaceWrapper) AdminEventTypesCreate(c *gin.Context) {

	c.Set(string(ApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AdminEventTypesCreate(c)
}

// AdminEventTypesGet operation middleware
func (siw *ServerInterfaceWrapper) AdminEventTypesGet(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug EventTypeSlug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", c.Param("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter slug: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(ApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AdminEventTypesGet(c, slug)
}

// AdminEventTypesUpdate operation middleware
func (siw *ServerInterfaceWrapper) AdminEventTypesUpdate(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug EventTypeSlug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", c.Param("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter slug: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(ApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AdminEventTypesUpdate(c, slug)
}

// AdminSettingsGet operation middleware
func (siw *ServerInterfaceWrapper) AdminSettingsGet(c *gin.Context) {

	c.Set(string(ApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AdminSettingsGet(c)
}

// AdminSettingsUpdate operation middleware
func (siw *ServerInterfaceWrapper) AdminSettingsUpdate(c *gin.Context) {

	c.Set(string(ApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AdminSettingsUpdate(c)
}

// PublicEventTypesList operation middleware
func (siw *ServerInterfaceWrapper) PublicEventTypesList(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PublicEventTypesList(c)
}

// PublicEventTypesGet operation middleware
func (siw *ServerInterfaceWrapper) PublicEventTypesGet(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug EventTypeSlug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", c.Param("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter slug: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PublicEventTypesGet(c, slug)
}

// PublicEventTypesBook operation middleware
func (siw *ServerInterfaceWrapper) PublicEventTypesBook(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug EventTypeSlug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", c.Param("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter slug: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PublicEventTypesBook(c, slug)
}

// PublicEventTypesSlots operation middleware
func (siw *ServerInterfaceWrapper) PublicEventTypesSlots(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug EventTypeSlug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", c.Param("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter slug: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PublicEventTypesSlots(c, slug)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/admin/bookings", wrapper.AdminBookingsList)
	router.DELETE(options.BaseURL+"/admin/bookings/:id", wrapper.AdminBookingsCancel)
	router.GET(options.BaseURL+"/admin/event-types", wrapper.AdminEventTypesList)
	router.POST(options.BaseURL+"/admin/event-types", wrapper.AdminEventTypesCreate)
	router.GET(options.BaseURL+"/admin/event-types/:slug", wrapper.AdminEventTypesGet)
	router.PATCH(options.BaseURL+"/admin/event-types/:slug", wrapper.AdminEventTypesUpdate)
	router.GET(options.BaseURL+"/admin/settings", wrapper.AdminSettingsGet)
	router.PUT(options.BaseURL+"/admin/settings", wrapper.AdminSettingsUpdate)
	router.GET(options.BaseURL+"/event-types", wrapper.PublicEventTypesList)
	router.GET(options.BaseURL+"/event-types/:slug", wrapper.PublicEventTypesGet)
	router.POST(options.BaseURL+"/event-types/:slug/bookings", wrapper.PublicEventTypesBook)
	router.GET(options.BaseURL+"/event-types/:slug/slots", wrapper.PublicEventTypesSlots)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7HyLcty2kvaroPifqkh/yNHcJEvj2qqVL4m1a8feSNmzKY92hSGaQ0QkwACg5IlXVechzhOeJ9lCg+Rw",
	"SM5oxnZ8OXZVqmINAKLR6MvXjQbeeqFMMylAGO1N3no6jCGl+M9HUl5zMbf/ZKBDxTPDpfAm3imZuSai",
	"IJSK9Tzfgzc0zRLQ3uT1Wy9UQA2wU+NNvGF/eBT0D4P+ycVgPBmOJoPB9/3RpN/3fI/litpvvuAiN6DP",
	"Bc10LI03GfV9D25AmItFBj/RFLyJdyaMkiSkSeLVGs+TfO5NPG4bg6JxnoM2T1PKE2/i/UYF9JiEfy0o",
	"7IUyLfsUX/43KoA8kVD9LI1diPe8WGUk1S1VjBhJwpgaY3+jM5kbYmIgmZK/QWgsEzjzJt7hbBQd02EY",
	"wINoHIzpYBachIcsGEYP4HjWp0dsFHq+pw1V5oIjASWPBsOLQX/St/8VPLq79L1MyQyU4YC7UuNtc1/O",
	"Qd2ACqjWfC6AEezKpSCGp6ANTTNLZCRVSu3OMGogsE2e75lFZgnRRtkdv9uwNW89miQvI9znvyiIvIn3",
	"/w6WMnRQCNDBk9UP4Eoa5BbfJDJCRuKeEkvJd5qU8xNqKmmztPqEC5K6b/YsoQ0xebvLJIKm0Jyg18WN",
	"hrhty4OnK8M6OJDk8zZhLYrIC7ogMyDa0AQId/21Hcs1SagBRYBxAwwZUpf+e8iznU4ZU6B1NbJkY4sH",
	"ddXoaLayv3m6wp6cMdu9Jv7NLSv6EeyCHCB7Z+cvyfFRf0BuuYmJjCINZn9bab7zPQW/51wB8yavLaXN",
	"HW2KUZ2+9bpQ59gK3/2all5W5MiZtRN28cUKH2OnLgawhTU6hQJba0ME3FZCkQsGilBRk5mWCf4INrD3",
	"HlbsEwnpBql7HEsNguhEmprk9ciLXBsCb2hokgVJqQljy3l6Q3lCZwm4AQpMrqzJnS0K5ZQmyHh4bVVT",
	"sExyYd5RWuuCuEbcNojYGbvfTZRixRkIwyMOiuz98svZE3IzXlWxPEfVaXH1MTU0kfOfQWdS6A7eli0o",
	"1Ogz81nCQye/Adq80H2jJceVXro/m0Dk95yH12TUD5xLIIgDWB6i67CCagV2Dvi/ayFvCdAwJtLEqECM",
	"MK7DXGuykLmqe/KGyjtEIjqAiG7hjzu/SeYPMsw1MHJUkVlMa4m0Lo7oDEIe8ZAYmfGwk4CjJQFPADLC",
	"+A0s52cAWYA/tad/omRmvaZl/uCwdJ6WI1RfEyoWJi60uTXp4LCa9GUU8RBILHOll/NK/DVwv1o1tzL9",
	"hxR2xNPcqvzBC6lDedthA+pb29rZJCFhrhQIq3Y0NPym7iI1wgDGdZbQBZGKgUL8ZSDV9xmUVyh7lWu2",
	"AlxINFWKLvDvahHbevozKuhFOart6M9Ofzol5VdRAxCSERMrmc/jEkqevjojVKEUg8oUGGCEi17LJlT0",
	"+XUmdpmBx4nUwJ7QRReKZ5Z3gtzGPIyJkKUh0CSkgsgwzFVLHbWhJrd+IcQPd+xq2eOtByJPLbVF18st",
	"LJ0d2bWMJ3RxnkjTISgvBbh1RC3Dqwqr01oEQ69b81coz/j513Uv1j9Z8WJ+o220rq3h/VbbxhvGHa6M",
	"u/SX7JYZiA5mswI/bCmkWj6xA9ry+ZgmIBhVxH7QqpblZShFxOe5AlaJLgJM3b0Tp6sucelDdWH2ucad",
	"2nPojSiIEgiNXjfXfo88TTOzILlIQGty5ZhxRf6FXFl2XK1o/HZRTVPRl8K6MZShi3PXsSmyyP/qMyVr",
	"1klwNVnDH+PvVoIp0VzMEyfRxS4gM7skutAulAy/VDLfEzIowAlPuFl0qJ3vNWOzFkmvpOY1k1v6BbS6",
	"t7FMYBmC1fABF2ZkdSnlgqeWukE1t7Voc1B28hVA14YKPzwmh6PhkIDtRqjrtzINFBi7taynSknV/iT+",
	"TEDcQCIzWGI1K5VULIiQIhi+ebPeXoSS4USJNP+Tiwr62ZWC1nRuGy+seONecW1taSLF3GKMsnOPvEqA",
	"asCtJJQwHkWg0J9h0NkR6OOsHcJiVQxwTbYLLiNTcq5omlLDQxJTwZLCo7d4VFHc/PCzPKUiUEAZTlD0",
	"e0g0jcBihdLZGmkRLck1KN27F73iIpazdmnG0hO3TYpYCYs1ueGaW+qMRN2Qt8KCVS7CJGfgLEmBFaKE",
	"zvdbO+kavYlROfhfBJhsiUW5hCq6mUmZABWYtKkv6O29SZ177V4zhVNS3RVZFYmRHdIhTffvAnHhwpv6",
	"UtqE+yUbNgrUrvF1LZwmFzGQKzfJFQoTYRDRPDEInK38WOhUZtjaEOMTBgBtlPC1iMVGaShTd6tb88vP",
	"z4NIcRAsWdQjYOccVkTiubwFFVINPqFJFlORp6B46JN4kcUgAg0ZVRTTcL6X0jfPQcxN7E2OxugSyz8H",
	"vpdRY0DZ6f/7NQ3+6Acnl9/vBdU/9///XzrdW7mSXzK2Wa4zqgynSbIgue2KEr66llOxIDqfWRwmIxJx",
	"SJgmqUszZgo0CPNwKmTKjY1BinYbmuQijKmYA+uRp4zjp68a23BFmATrBA2hUQShIfCGa9t1KqoQYw9t",
	"Z5l6CKlSHDThRlujvsz+6iLXtl+bzkrElXWzOsddnorCHWiaojtMqUF7nAv+ew7CgkeVJ6CtB1mvsU0l",
	"GC9jX8dw5hwC+RoMc0uNnsUv0rbE/ZUmSRAmMrx2eVqqybNnkxcvyN5wHPsWB2kIpWB6328EtesjjBX1",
	"2HvdH1xOp+x/h6/7wehyf/K6HxzaHzo1ZCUKbxG7GoQvdd0n0Jv3yHQ1YTH1OvFTGUO1v15mqMNmLPXr",
	"r7/+Grx4ETx5gsK5CydWopoucl5mIDZE95gtt8F8BoLcSoXKdssFk7c9cgWCXZE018YdLiiOOc45ek0b",
	"sFGBQZcyV+20nGDexBscuxgWO3kTDwNm7/6wFUdvFkmUt7vq01t3buQekIBtMw/lbD4S2OVMXlrAeQ6Y",
	"/u5KRtjmoNxLFwsXnXvkHEM7I4UNNGSuwnagsTZ55nvF5j3DRJuNdxVnbt+LrXiw1Vb4XirF6sDjLQdq",
	"anJVDG2lgXxP52J9o4lzpd9tWpPDO468BSbebexdW2TrKcHtE4Htfds09q+1vo8WVq03JP5WPtwlq808",
	"507RFZ4uaItNa+n6IkdP9mhySxe6CLX27wG/X0hc9VWD5PNEmleYY9rhEKfzkIucOtkI5Q0oXR2cDcbW",
	"xWkIc4zOGV3ojrTsojM/2z+p5WfrSdHKvrRTuv3dhww6s8CDDVngwYYs8GBDFnhwMRhvbBttzAL7nziD",
	"fV+WuoO+USd9o4vBYN082DZa2zbanYZxJw3jDTwaXwyONraN1rY92J2+w076DjfQd7hhDw+be7gVDUe7",
	"q82D3Yccd670eMNKjzdIynFTm7Za6UknDScbJP+kKXWrbbtrxXCdkWqm8LvGdlqr4QZrNWxZq61o7LQs",
	"w2FTMzrPqjbBWYxBniIoW5nLNZwX+KzmAroOvxYdGHwwxsgHhMGMQqRkSq5qX72yKOOqmv/KJzJhoA2J",
	"uNJm61Pk6kTyUx4fd54VrzD3/Y8Gn1NtXChbHLGWORs3S5F91wgES+cPv+c00Q22f08Go8Lx3zX2+f2p",
	"/MFu3pZk+psPODdA7hrNdS77ThS7gFUB6deE6MvTvu80sYtkeQITAhyhr7OgPnGZSAzhcbNvaEJeYwTj",
	"W9y13yNPuP1uygVmqWaL6qzUirMUsAVrl4UC1gps6lmmHO4ul+urhSztHBHAdbIosw+uVKRarF8U9AlA",
	"jV2QDFT9PP8W4LoFFL/Fvn9m7Nuys0t2bxG8OgmqcXr7MXUm7zAq332m+pbsMGq5G9sPWtmIbYc1TFDB",
	"zCUF9c/WVuOXW1XjZcWgtnWyzIMwV9wszi0RbrdPM/7vsDjNTWz/4laDY6AMlFfF1v8VnLKUi+BCXmPt",
	"Qen/cKR3Zz/MRSQ7LN6rM2t0jaKhqcLIm1rKtDTaGtQND4tjOHfKm1JB56BdymIqsAoMswM3HG51Vbv0",
	"sExdzJS81dBROoaDbHcSKYCpQHRTugQBbwxxEEJbd5bcV6i1PIf+Tk9FzaOs+Gy/OJaw5plq0lXNjNlm",
	"bhKol+OcOz54vmejacfEfm/Q61vRsvpKM+5NvBH+hInzGDfxgNoNOiiZghW30HFj4DnXhtAkIXkWytRy",
	"vjqgoaGSGtmtFjX2+URLVXiZZYnPVFAdgmBczHvklUUMy+8owKOgsuwC99SyDsskMjq3XotL69vIzQAd",
	"VgYuY3FmzRaKWlHNqi29nlUOl4rAhQ37fVcuIQwIByayLOEhfuLgN+3yOYUD+XY95cNeT/HXc3Mw6R9P",
	"xuP7uXnUwc36CXeTmcuj7gYvQ6oSqXuKplzBHxs4+hg7kp9dx5IzJ2wYjmBMg8HsMArG4TEEdDR7EBxH",
	"fXYEQ3oSDmbrODNqBqHrODPoX1i2DCeD4/s5Mzhsc6ZRh9tkzkpBboM/lF/LnqGCXtMNzDnl15JcYK+m",
	"xJ19x0gib8p6IEzKZlK7rLEFeDqWmSth0JV9r0yLAZpaYxdobsB3h9RhnlCVLAhVMhessDMFOHTH1syN",
	"C6VUrDQV1PahCVRC/QCOoxPanwXDcMSCMRxGAf45CIdsBOPokB6t3brDZqZp09adTDDQ/4hCrWnas75M",
	"bNiyc5qSR7ZPc8P+AzPvmGL/x9/+Tn63bVwKXbMPSlKW0qxiZZ8OZksuHtEHs+A4PGFBHwbRkI5m4/CQ",
	"rWPlSTMtYMGkAzgIJrYJrMtbh624+q55ju5ZcGBxko3eY6qJzsMQgBX3oMb9wRZ+YUndxuw7VhZ2kDDu",
	"D8gvguYmlor/AWxC0PMSY6GR9XEp1zbKs0EcFzc04ay3grzQIdUx1+tLTJ3QOWZc0PtNSOn/vEs7tuHd",
	"D95ydud8ewJdR9OPqQghsUFk0807gFVdANFEQSpvgJE9aRGXugZGQhydALMiNBUab498p0kYSx7CPqoo",
	"N9oVAGAF5AxCaUETT1NgnBqwCl5VB9M55eIeP+8oRkSjaAoGlIv8EI5alLMEo3glZYmWXWXfdrtau5Bm",
	"ed5AFeM2I+vIpZArawo1CLascS4k0iezQsMcfK7Ka3INUZ70yGcuo5a48ccgbkx+kob8YO3/xFkkx0Bg",
	"1UH5sqAIK4msdCKiLrC+bxfBRXUc+YH0a3k7aQsAXQ8wrKmdSROXwQdqSEEeNnbdXenQhurM7wPh3i+v",
	"+tXfTPRHv1i1iZiPd82qRkhEE92i5BlnDIRLfWOe053bPyRGzucJFq4a6Q71ddxJ0MmSJ8+lmAc2eq0A",
	"3pKspGx7F0e/4QbW1+zqny4NiXd553uZ1B12x5U2r6lbxqvhZV2XK4Isw/mGqZqKvcIsSWXt636P/AS3",
	"yYIU+Hc1b6KqdMpsUZZD32u6iiJs56NBm0eSLXaxW5/4MuW2UtOoOb9bzeFZe3HXst+D3fjwGVnCXbmy",
	"k0qjN3GSXQEA22EGICrBpJpQ24wiiCag/+ebgB9BgOIhGff75BFl5OeC/AjRcmItIZ7CZbmxCoU2wEWs",
	"EeVJroonKz5z1HfyMYg7IY+liBIemiboc/XleDhnm7VLkhaXgYk21ECPPC3OgyZTwXJHXmH3ylsZcACM",
	"G99FJDRRQNkCIx1gxY8WwxQJ3Ixq409FrRxuBiFNYQnbZmBuoXgfoCx6uuFwW2WTMW2dz1Ju3t/qd2LQ",
	"g7d2fXdroeiPYJYXCOsrWTjG1Cx9DSvfY71/BLNVFFYUoL1bHNasbbt8P6T7RQLdP9Wi9r7Fmp9PrNkC",
	"eNSEcccV3NU7PPAON3h6U7HFHZ3C3pZ3dJYnN3smhgW5tkjAxGANbeNSDjHU7mrjuaJNV3WKi5tTgVd1",
	"avdzqMugpNR0X9XZaKSK+1Cfxk69K6htGothy1jE1LyDYSiYsRUA/TLNajenPp1Z/QY8v3IX8A00f16g",
	"WdcuaK2FypgYK/jjKkzKYWSvKrX8HgvQltVrLi+3DjaXF8McaH4/W/vtKtjnchVsWx+yejfwq85hVlxA",
	"fJubrstEWUJDV8sMwnAFTSVkMsxTC2LJf1bebLIsgi7Tm3TqyHT1VhYWPERT7eqW3ENBhNGFv81116ko",
	"77uSpy04XBYyuTvtrgLKmV1NYlBwj1GoQOo7Q8b3MQlHq8KOZTxbmYSTLQd+YJOw7bRtk7DtyC6TsN3Y",
	"9zIJHxiSf5OJfwKZ+BZufFEuzQLNbWoDXq3empYR+hL3fNcSufbIz1gZq4kUyaL16GUdX2ufZEm+9sE8",
	"ot0zKJFChmPlDknoDIoi5raDalwRf48yg+02sflQ7I7Sf7fcFUd5ezN2SpK3asPLXHmPnImOwnHHF4ax",
	"1VTYUNK2EhPLfB4TzJa5gNHVSAWaM6yXLkvSQyosgMiUnCHySe/fkS8o/77dXK3XV3c3gF9wpnhL8V0p",
	"3O8uADjHqJnQKowuHqxqiW1REoASSRQEhbHGOw3UuGzscm1XVV2nS9saniSEOgvffPR6j4vAXYJz70I6",
	"vDEVGCP7yJh6poAISeQNqIRm5bs0i1bW2a9RPhXF9AUHyUtRJTiKLSleJOCajPsnmFVYPmNrfy1Oix9O",
	"BdrMhGM2JJZ5YrcxiMCEceuVTTx+1tf4O24lVsvgs43dpYtNpX0k5fUXkI3eqUjyQ9c17DT5t/KBVVj1",
	"LVH6tSdKt3Uk1VvNG/Ogg3HA6KI9+2afUmr9VNDyzRdhKBcrr77U7uL3CN6YJ0BVwssHxmpp2KlIZQqi",
	"4Grhn0qPQUXLV5A99CAVVfu+O0eiCz0VZfE6BpR2I6rEUpnH0bmKaFjYgsqz/eNvf3dIjip0jPhG9fKd",
	"tgwUsqp6jBoPXgkX2gBl97sG92bAPxWi63g76GsHdRhdWsDV9R7WcxnShDDA56hTtDrY1/O9XCXexIuN",
	"ySYHB4ntF0ttJqN+cZWmmOltKSPN2PTObzbVj0jarVXZe62pWMXd5d3/BQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
