package domain

import (
	"time"
)

// DaySlot is one day in a SlotPickerResponse: a calendar date plus zero or
// more available start instants. Status reflects whether the day is closed,
// has availability, or is open-but-fully-booked.
type DaySlot struct {
	Date   time.Time // start-of-day in the configured timezone
	Status DayPickerStatus
	Slots  []time.Time // empty unless Status == DayPickerOpen
}

// DayPickerStatus mirrors the contract's DayStatus enum (open / closed /
// no-availability) with explicit names independent of the API package.
type DayPickerStatus string

const (
	DayPickerOpen           DayPickerStatus = "open"
	DayPickerClosed         DayPickerStatus = "closed"
	DayPickerNoAvailability DayPickerStatus = "no-availability"
)

// GenerateSlotsInput is the pure input bundle for slot generation: no I/O,
// no clock — the caller decides "now" and supplies all existing bookings.
type GenerateSlotsInput struct {
	Timezone        *time.Location
	WorkingHours    WorkingHours
	DurationMinutes int
	Now             time.Time
	Bookings        []Booking
}

// GenerateSlotsResult bundles the 14-day window and per-day breakdown.
type GenerateSlotsResult struct {
	WindowStart time.Time // start-of-day, in TZ
	WindowEnd   time.Time // start-of-day of the 14th day (inclusive)
	Days        []DaySlot // always 14 entries
}

// GenerateSlots produces the 14-day slot picker view for one event type,
// honouring the cross-event-type non-overlap invariant.
//
// Algorithm (mirrors business-description.md §4.2):
//
//  1. today := start-of-day(Now, TZ); window covers today..today+13.
//  2. For each day d in the window:
//     a. Look up the working hours for d's weekday.
//     b. If closed → emit DaySlot{Closed, nil} and continue.
//     c. Otherwise: build a grid of slot starts spaced by DurationMinutes,
//     starting at openAt, while slot_start + duration ≤ closeAt.
//     d. Drop any slot start before Now (past slots).
//     e. Drop any slot whose interval overlaps any existing booking
//     (any event type) — that's the cross-ET non-overlap rule.
//     f. Status is "open" if the day was open and at least one slot
//     survived; "no-availability" if the day was open but every slot
//     was dropped.
func GenerateSlots(in GenerateSlotsInput) GenerateSlotsResult {
	today := StartOfDayInTZ(in.Now, in.Timezone)
	durationSpan := time.Duration(in.DurationMinutes) * time.Minute

	days := make([]DaySlot, 14)
	for i := 0; i < 14; i++ {
		dayStart := today.AddDate(0, 0, i)
		weekday := dayStart.In(in.Timezone).Weekday()
		wd := in.WorkingHours.ForWeekday(weekday)

		if wd.Status == DayClosed {
			days[i] = DaySlot{Date: dayStart, Status: DayPickerClosed, Slots: []time.Time{}}
			continue
		}

		startH, startM := ParseHHMM(wd.Start)
		endH, endM := ParseHHMM(wd.End)
		openAt := WallClockInTZ(dayStart, startH, startM, in.Timezone)
		closeAt := WallClockInTZ(dayStart, endH, endM, in.Timezone)

		slots := make([]time.Time, 0)
		for t := openAt; !t.Add(durationSpan).After(closeAt); t = t.Add(durationSpan) {
			if t.Before(in.Now) {
				continue
			}
			candidate := Interval{Start: t, End: t.Add(durationSpan)}
			conflicts := false
			for _, b := range in.Bookings {
				if Overlaps(candidate, b.Interval()) {
					conflicts = true
					break
				}
			}
			if !conflicts {
				slots = append(slots, t)
			}
		}

		status := DayPickerOpen
		if len(slots) == 0 {
			status = DayPickerNoAvailability
		}
		days[i] = DaySlot{Date: dayStart, Status: status, Slots: slots}
	}

	return GenerateSlotsResult{
		WindowStart: today,
		WindowEnd:   today.AddDate(0, 0, 13),
		Days:        days,
	}
}

// IsOnSlotGrid reports whether candidate is one of the discrete slot start
// instants generated by GenerateSlots for the supplied event type duration.
// Used by booking submission to reject startTimes that don't align to the
// grid (e.g. 09:07 for a 30-minute event with 09:00 working start).
func IsOnSlotGrid(candidate time.Time, dayStart time.Time, wd WorkingDay, durationMinutes int, loc *time.Location) bool {
	if wd.Status != DayOpen {
		return false
	}
	startH, startM := ParseHHMM(wd.Start)
	endH, endM := ParseHHMM(wd.End)
	openAt := WallClockInTZ(dayStart, startH, startM, loc)
	closeAt := WallClockInTZ(dayStart, endH, endM, loc)
	durationSpan := time.Duration(durationMinutes) * time.Minute

	for t := openAt; !t.Add(durationSpan).After(closeAt); t = t.Add(durationSpan) {
		if t.Equal(candidate) {
			return true
		}
	}
	return false
}
